cc_library(
  name = "common_conversions",
  srcs = ["common_conversions/conversions.h"],
  visibility = ["//visibility:public"],
)

cc_library(
  name = "TeaFIR",
  srcs = ["FIR/TeaFIR.h"],
  deps = ["common_conversions"],
  visibility = ["//visibility:public"],
)