workspace(name = "teadsp")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    url = "https://github.com/google/googletest/archive/release-1.10.0.zip",
    sha256 = "94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91",
)

new_local_repository(
    name = "fftw3",
    path = "C:/Users/TJ/myappsource/fftw-3.3.5-dll64",
    build_file = "C:/Users/TJ/myappsource/fftw-3.3.5-dll64/BUILD",
)