cc_library(
    name = "TeaFIR",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    deps = ["//TeaCommon:TeaCommon"],
    visibility = ["//consoleTests/TestBaz:__pkg__",
                  "//Test:__pkg__"],
)