cc_test(
  name = "test-lfo",
  size = "small",
  srcs = ["TeaLFO_unittest.cpp"],
  deps = ["@googletest//googletest-release-1.10.0:gtest",
          "@googletest//googletest-release-1.10.0:gtest_main",
          "//TeaLFO:TeaLFO",
          "//TeaCommon:TeaCommon"],
)

cc_test(
  name = "test-common",
  size = "small",
  srcs = ["TeaCommon_unittest.cpp"],
  deps = ["@googletest//googletest-release-1.10.0:gtest",
          "@googletest//googletest-release-1.10.0:gtest_main",
          "//TeaCommon:TeaCommon"],
)

